# Generated by Django 5.2.5 on 2026-03-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='create_post',
            new_name='CreatePost',
        ),
        migrations.RenameField(
            model_name='createpost',
            old_name='pub_date',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='context',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='pub_date',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
